import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Preloader from '@/app/components/Preloader';
import Navbar from '@/app/components/Navbar';
import PhotoReveal from '@/app/effects/DraggablePhoto';
import SmoothScroll from '@/app/components/SmoothScroll';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#0E0E0E] text-white">
       
        <Preloader />
        
        <Navbar />
        {children}
        
      </body>
    </html>
  )
}